// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package jobicy

import "net/url"

type ListRemoteJobsParams struct {
	// Number of listings to return (default: 50, range: 1-50)
	Count int
	// Filter by job region (default: all regions)
	Geo string
	// Filter by job category (default: all categories)
	Industry string
	// Search by job title and description (default: all jobs)
	Tag string
}

// JobsList defines a model
type JobsList struct {
	// The version of the API in use
	APIVersion       string  `json:"apiVersion"`
	DocumentationURL url.URL `json:"documentationUrl"`
	FriendlyNotice   string  `json:"friendlyNotice"`
	JobCount         int     `json:"jobCount"`
	XRayHash         string  `json:"xRayHash"`
	ClientKey        string  `json:"clientKey"`
	LastUpdate       string  `json:"lastUpdate"`
	Jobs             Jobs    `json:"jobs"`
}

// Jobs defines a model
type Jobs []Job

// Job defines a model
type Job struct {
	// Unique Job ID
	ID int `json:"id"`
	// Job link
	URL url.URL `json:"url"`
	// Job slug
	JobSlug string `json:"jobSlug"`
	// Job title
	JobTitle string `json:"jobTitle"`
	// Company name
	CompanyName string `json:"companyName"`
	// Company logo link
	CompanyLogo url.URL `json:"companyLogo"`
	// Job function (industry)
	JobIndustry []string `json:"jobIndustry"`
	// Job type
	JobType JobTypes `json:"jobType"`
	// Geographic restriction for employment (or Anywhere if not applicable)
	JobGeo string `json:"jobGeo"`
	// Seniority level (or Any if not applicable)
	JobLevel string `json:"jobLevel"`
	// Excerpt job description (max 55 characters)
	JobExcerpt string `json:"jobExcerpt"`
	// Full job description (HTML)
	JobDescription string `json:"jobDescription"`
	// Publication date and time
	PubDate string `json:"pubDate"`
	// Annual min salary (if applicable)
	AnnualSalaryMin *string `json:"annualSalaryMin"`
	// Annual max salary (if applicable)
	AnnualSalaryMax *string `json:"annualSalaryMax"`
	// ISO 4217 salary currency code (if applicable)
	SalaryCurrency *string `json:"salaryCurrency"`
}

// Job type
type JobTypes []JobType

// JobType defines a model
type JobType string
