// This file provides types for the API.
//
// Code generated by github.com/MarkRosemaker DO NOT EDIT.

package jobicy

import "net/url"

type ListRemoteJobsParams struct {
	Geo      string
	Industry string
	Tag      string
	Count    int
}

// ListRemoteJobsOkJSONResponse defines a model
type ListRemoteJobsOkJSONResponse struct {
	APIVersion       string  `json:"apiVersion"`
	DocumentationURL url.URL `json:"documentationUrl"`
	FriendlyNotice   string  `json:"friendlyNotice"`
	JobCount         int     `json:"jobCount"`
	XRayHash         string  `json:"xRayHash"`
	ClientKey        string  `json:"clientKey"`
	LastUpdate       string  `json:"lastUpdate"`
	Jobs             Jobs    `json:"jobs"`
}

// Jobs defines a model
type Jobs []Job

// Job defines a model
type Job struct {
	ID              int      `json:"id"`
	URL             url.URL  `json:"url"`
	JobSlug         string   `json:"jobSlug"`
	JobTitle        string   `json:"jobTitle"`
	CompanyName     string   `json:"companyName"`
	CompanyLogo     url.URL  `json:"companyLogo"`
	JobIndustry     []string `json:"jobIndustry"`
	JobType         []string `json:"jobType"`
	JobGeo          string   `json:"jobGeo"`
	JobLevel        string   `json:"jobLevel"`
	JobExcerpt      string   `json:"jobExcerpt"`
	JobDescription  string   `json:"jobDescription"`
	PubDate         string   `json:"pubDate"`
	AnnualSalaryMin *string  `json:"annualSalaryMin"`
	AnnualSalaryMax *string  `json:"annualSalaryMax"`
	SalaryCurrency  *string  `json:"salaryCurrency"`
}
